VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "PUSItemForPUSBucket"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Public pn As String
Public duns As String
Public fup_code As String
Public pus_date As Date
Public eda_date As Date
Public qty As Long
Public nm As String


