VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "QTItem"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Public pus_bucket As PUSBUcket
Public country_code As String
Public resp As String
Public ppap_status As String

Public pn As String
Public duns As String
Public fup_code As String


Public supp_nm As String
Public del_conf As String

